
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Engine` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Engine
 * 
 */
export type EngineModel = runtime.Types.Result.DefaultSelection<Prisma.$EnginePayload>

export type AggregateEngine = {
  _count: EngineCountAggregateOutputType | null
  _min: EngineMinAggregateOutputType | null
  _max: EngineMaxAggregateOutputType | null
}

export type EngineMinAggregateOutputType = {
  id: string | null
  name: string | null
  title: string | null
  icon: string | null
  url: string | null
  uid: string | null
}

export type EngineMaxAggregateOutputType = {
  id: string | null
  name: string | null
  title: string | null
  icon: string | null
  url: string | null
  uid: string | null
}

export type EngineCountAggregateOutputType = {
  id: number
  name: number
  title: number
  icon: number
  url: number
  uid: number
  _all: number
}


export type EngineMinAggregateInputType = {
  id?: true
  name?: true
  title?: true
  icon?: true
  url?: true
  uid?: true
}

export type EngineMaxAggregateInputType = {
  id?: true
  name?: true
  title?: true
  icon?: true
  url?: true
  uid?: true
}

export type EngineCountAggregateInputType = {
  id?: true
  name?: true
  title?: true
  icon?: true
  url?: true
  uid?: true
  _all?: true
}

export type EngineAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Engine to aggregate.
   */
  where?: Prisma.EngineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Engines to fetch.
   */
  orderBy?: Prisma.EngineOrderByWithRelationInput | Prisma.EngineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EngineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Engines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Engines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Engines
  **/
  _count?: true | EngineCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EngineMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EngineMaxAggregateInputType
}

export type GetEngineAggregateType<T extends EngineAggregateArgs> = {
      [P in keyof T & keyof AggregateEngine]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEngine[P]>
    : Prisma.GetScalarType<T[P], AggregateEngine[P]>
}




export type EngineGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EngineWhereInput
  orderBy?: Prisma.EngineOrderByWithAggregationInput | Prisma.EngineOrderByWithAggregationInput[]
  by: Prisma.EngineScalarFieldEnum[] | Prisma.EngineScalarFieldEnum
  having?: Prisma.EngineScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EngineCountAggregateInputType | true
  _min?: EngineMinAggregateInputType
  _max?: EngineMaxAggregateInputType
}

export type EngineGroupByOutputType = {
  id: string
  name: string
  title: string
  icon: string
  url: string
  uid: string
  _count: EngineCountAggregateOutputType | null
  _min: EngineMinAggregateOutputType | null
  _max: EngineMaxAggregateOutputType | null
}

export type GetEngineGroupByPayload<T extends EngineGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EngineGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EngineGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EngineGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EngineGroupByOutputType[P]>
      }
    >
  >



export type EngineWhereInput = {
  AND?: Prisma.EngineWhereInput | Prisma.EngineWhereInput[]
  OR?: Prisma.EngineWhereInput[]
  NOT?: Prisma.EngineWhereInput | Prisma.EngineWhereInput[]
  id?: Prisma.StringFilter<"Engine"> | string
  name?: Prisma.StringFilter<"Engine"> | string
  title?: Prisma.StringFilter<"Engine"> | string
  icon?: Prisma.StringFilter<"Engine"> | string
  url?: Prisma.StringFilter<"Engine"> | string
  uid?: Prisma.StringFilter<"Engine"> | string
}

export type EngineOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  title?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  url?: Prisma.SortOrder
  uid?: Prisma.SortOrder
}

export type EngineWhereUniqueInput = Prisma.AtLeast<{
  name?: string
  AND?: Prisma.EngineWhereInput | Prisma.EngineWhereInput[]
  OR?: Prisma.EngineWhereInput[]
  NOT?: Prisma.EngineWhereInput | Prisma.EngineWhereInput[]
  id?: Prisma.StringFilter<"Engine"> | string
  title?: Prisma.StringFilter<"Engine"> | string
  icon?: Prisma.StringFilter<"Engine"> | string
  url?: Prisma.StringFilter<"Engine"> | string
  uid?: Prisma.StringFilter<"Engine"> | string
}, "name">

export type EngineOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  title?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  url?: Prisma.SortOrder
  uid?: Prisma.SortOrder
  _count?: Prisma.EngineCountOrderByAggregateInput
  _max?: Prisma.EngineMaxOrderByAggregateInput
  _min?: Prisma.EngineMinOrderByAggregateInput
}

export type EngineScalarWhereWithAggregatesInput = {
  AND?: Prisma.EngineScalarWhereWithAggregatesInput | Prisma.EngineScalarWhereWithAggregatesInput[]
  OR?: Prisma.EngineScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EngineScalarWhereWithAggregatesInput | Prisma.EngineScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Engine"> | string
  name?: Prisma.StringWithAggregatesFilter<"Engine"> | string
  title?: Prisma.StringWithAggregatesFilter<"Engine"> | string
  icon?: Prisma.StringWithAggregatesFilter<"Engine"> | string
  url?: Prisma.StringWithAggregatesFilter<"Engine"> | string
  uid?: Prisma.StringWithAggregatesFilter<"Engine"> | string
}

export type EngineCreateInput = {
  id: string
  name: string
  title: string
  icon: string
  url: string
  uid: string
}

export type EngineUncheckedCreateInput = {
  id: string
  name: string
  title: string
  icon: string
  url: string
  uid: string
}

export type EngineUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  uid?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EngineUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  uid?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EngineCreateManyInput = {
  id: string
  name: string
  title: string
  icon: string
  url: string
  uid: string
}

export type EngineUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  uid?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EngineUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  uid?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EngineCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  title?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  url?: Prisma.SortOrder
  uid?: Prisma.SortOrder
}

export type EngineMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  title?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  url?: Prisma.SortOrder
  uid?: Prisma.SortOrder
}

export type EngineMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  title?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  url?: Prisma.SortOrder
  uid?: Prisma.SortOrder
}



export type EngineSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  title?: boolean
  icon?: boolean
  url?: boolean
  uid?: boolean
}, ExtArgs["result"]["engine"]>

export type EngineSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  title?: boolean
  icon?: boolean
  url?: boolean
  uid?: boolean
}, ExtArgs["result"]["engine"]>

export type EngineSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  title?: boolean
  icon?: boolean
  url?: boolean
  uid?: boolean
}, ExtArgs["result"]["engine"]>

export type EngineSelectScalar = {
  id?: boolean
  name?: boolean
  title?: boolean
  icon?: boolean
  url?: boolean
  uid?: boolean
}

export type EngineOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "title" | "icon" | "url" | "uid", ExtArgs["result"]["engine"]>

export type $EnginePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Engine"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    title: string
    icon: string
    url: string
    uid: string
  }, ExtArgs["result"]["engine"]>
  composites: {}
}

export type EngineGetPayload<S extends boolean | null | undefined | EngineDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EnginePayload, S>

export type EngineCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EngineFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EngineCountAggregateInputType | true
  }

export interface EngineDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Engine'], meta: { name: 'Engine' } }
  /**
   * Find zero or one Engine that matches the filter.
   * @param {EngineFindUniqueArgs} args - Arguments to find a Engine
   * @example
   * // Get one Engine
   * const engine = await prisma.engine.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EngineFindUniqueArgs>(args: Prisma.SelectSubset<T, EngineFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EngineClient<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Engine that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EngineFindUniqueOrThrowArgs} args - Arguments to find a Engine
   * @example
   * // Get one Engine
   * const engine = await prisma.engine.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EngineFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EngineFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EngineClient<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Engine that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EngineFindFirstArgs} args - Arguments to find a Engine
   * @example
   * // Get one Engine
   * const engine = await prisma.engine.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EngineFindFirstArgs>(args?: Prisma.SelectSubset<T, EngineFindFirstArgs<ExtArgs>>): Prisma.Prisma__EngineClient<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Engine that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EngineFindFirstOrThrowArgs} args - Arguments to find a Engine
   * @example
   * // Get one Engine
   * const engine = await prisma.engine.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EngineFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EngineFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EngineClient<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Engines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EngineFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Engines
   * const engines = await prisma.engine.findMany()
   * 
   * // Get first 10 Engines
   * const engines = await prisma.engine.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const engineWithIdOnly = await prisma.engine.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EngineFindManyArgs>(args?: Prisma.SelectSubset<T, EngineFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Engine.
   * @param {EngineCreateArgs} args - Arguments to create a Engine.
   * @example
   * // Create one Engine
   * const Engine = await prisma.engine.create({
   *   data: {
   *     // ... data to create a Engine
   *   }
   * })
   * 
   */
  create<T extends EngineCreateArgs>(args: Prisma.SelectSubset<T, EngineCreateArgs<ExtArgs>>): Prisma.Prisma__EngineClient<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Engines.
   * @param {EngineCreateManyArgs} args - Arguments to create many Engines.
   * @example
   * // Create many Engines
   * const engine = await prisma.engine.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EngineCreateManyArgs>(args?: Prisma.SelectSubset<T, EngineCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Engines and returns the data saved in the database.
   * @param {EngineCreateManyAndReturnArgs} args - Arguments to create many Engines.
   * @example
   * // Create many Engines
   * const engine = await prisma.engine.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Engines and only return the `id`
   * const engineWithIdOnly = await prisma.engine.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EngineCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EngineCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Engine.
   * @param {EngineDeleteArgs} args - Arguments to delete one Engine.
   * @example
   * // Delete one Engine
   * const Engine = await prisma.engine.delete({
   *   where: {
   *     // ... filter to delete one Engine
   *   }
   * })
   * 
   */
  delete<T extends EngineDeleteArgs>(args: Prisma.SelectSubset<T, EngineDeleteArgs<ExtArgs>>): Prisma.Prisma__EngineClient<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Engine.
   * @param {EngineUpdateArgs} args - Arguments to update one Engine.
   * @example
   * // Update one Engine
   * const engine = await prisma.engine.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EngineUpdateArgs>(args: Prisma.SelectSubset<T, EngineUpdateArgs<ExtArgs>>): Prisma.Prisma__EngineClient<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Engines.
   * @param {EngineDeleteManyArgs} args - Arguments to filter Engines to delete.
   * @example
   * // Delete a few Engines
   * const { count } = await prisma.engine.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EngineDeleteManyArgs>(args?: Prisma.SelectSubset<T, EngineDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Engines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EngineUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Engines
   * const engine = await prisma.engine.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EngineUpdateManyArgs>(args: Prisma.SelectSubset<T, EngineUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Engines and returns the data updated in the database.
   * @param {EngineUpdateManyAndReturnArgs} args - Arguments to update many Engines.
   * @example
   * // Update many Engines
   * const engine = await prisma.engine.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Engines and only return the `id`
   * const engineWithIdOnly = await prisma.engine.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EngineUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EngineUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Engine.
   * @param {EngineUpsertArgs} args - Arguments to update or create a Engine.
   * @example
   * // Update or create a Engine
   * const engine = await prisma.engine.upsert({
   *   create: {
   *     // ... data to create a Engine
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Engine we want to update
   *   }
   * })
   */
  upsert<T extends EngineUpsertArgs>(args: Prisma.SelectSubset<T, EngineUpsertArgs<ExtArgs>>): Prisma.Prisma__EngineClient<runtime.Types.Result.GetResult<Prisma.$EnginePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Engines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EngineCountArgs} args - Arguments to filter Engines to count.
   * @example
   * // Count the number of Engines
   * const count = await prisma.engine.count({
   *   where: {
   *     // ... the filter for the Engines we want to count
   *   }
   * })
  **/
  count<T extends EngineCountArgs>(
    args?: Prisma.Subset<T, EngineCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EngineCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Engine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EngineAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EngineAggregateArgs>(args: Prisma.Subset<T, EngineAggregateArgs>): Prisma.PrismaPromise<GetEngineAggregateType<T>>

  /**
   * Group by Engine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EngineGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EngineGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EngineGroupByArgs['orderBy'] }
      : { orderBy?: EngineGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EngineGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEngineGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Engine model
 */
readonly fields: EngineFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Engine.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EngineClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Engine model
 */
export interface EngineFieldRefs {
  readonly id: Prisma.FieldRef<"Engine", 'String'>
  readonly name: Prisma.FieldRef<"Engine", 'String'>
  readonly title: Prisma.FieldRef<"Engine", 'String'>
  readonly icon: Prisma.FieldRef<"Engine", 'String'>
  readonly url: Prisma.FieldRef<"Engine", 'String'>
  readonly uid: Prisma.FieldRef<"Engine", 'String'>
}
    

// Custom InputTypes
/**
 * Engine findUnique
 */
export type EngineFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * Filter, which Engine to fetch.
   */
  where: Prisma.EngineWhereUniqueInput
}

/**
 * Engine findUniqueOrThrow
 */
export type EngineFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * Filter, which Engine to fetch.
   */
  where: Prisma.EngineWhereUniqueInput
}

/**
 * Engine findFirst
 */
export type EngineFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * Filter, which Engine to fetch.
   */
  where?: Prisma.EngineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Engines to fetch.
   */
  orderBy?: Prisma.EngineOrderByWithRelationInput | Prisma.EngineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Engines.
   */
  cursor?: Prisma.EngineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Engines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Engines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Engines.
   */
  distinct?: Prisma.EngineScalarFieldEnum | Prisma.EngineScalarFieldEnum[]
}

/**
 * Engine findFirstOrThrow
 */
export type EngineFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * Filter, which Engine to fetch.
   */
  where?: Prisma.EngineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Engines to fetch.
   */
  orderBy?: Prisma.EngineOrderByWithRelationInput | Prisma.EngineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Engines.
   */
  cursor?: Prisma.EngineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Engines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Engines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Engines.
   */
  distinct?: Prisma.EngineScalarFieldEnum | Prisma.EngineScalarFieldEnum[]
}

/**
 * Engine findMany
 */
export type EngineFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * Filter, which Engines to fetch.
   */
  where?: Prisma.EngineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Engines to fetch.
   */
  orderBy?: Prisma.EngineOrderByWithRelationInput | Prisma.EngineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Engines.
   */
  cursor?: Prisma.EngineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Engines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Engines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Engines.
   */
  distinct?: Prisma.EngineScalarFieldEnum | Prisma.EngineScalarFieldEnum[]
}

/**
 * Engine create
 */
export type EngineCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * The data needed to create a Engine.
   */
  data: Prisma.XOR<Prisma.EngineCreateInput, Prisma.EngineUncheckedCreateInput>
}

/**
 * Engine createMany
 */
export type EngineCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Engines.
   */
  data: Prisma.EngineCreateManyInput | Prisma.EngineCreateManyInput[]
}

/**
 * Engine createManyAndReturn
 */
export type EngineCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * The data used to create many Engines.
   */
  data: Prisma.EngineCreateManyInput | Prisma.EngineCreateManyInput[]
}

/**
 * Engine update
 */
export type EngineUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * The data needed to update a Engine.
   */
  data: Prisma.XOR<Prisma.EngineUpdateInput, Prisma.EngineUncheckedUpdateInput>
  /**
   * Choose, which Engine to update.
   */
  where: Prisma.EngineWhereUniqueInput
}

/**
 * Engine updateMany
 */
export type EngineUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Engines.
   */
  data: Prisma.XOR<Prisma.EngineUpdateManyMutationInput, Prisma.EngineUncheckedUpdateManyInput>
  /**
   * Filter which Engines to update
   */
  where?: Prisma.EngineWhereInput
  /**
   * Limit how many Engines to update.
   */
  limit?: number
}

/**
 * Engine updateManyAndReturn
 */
export type EngineUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * The data used to update Engines.
   */
  data: Prisma.XOR<Prisma.EngineUpdateManyMutationInput, Prisma.EngineUncheckedUpdateManyInput>
  /**
   * Filter which Engines to update
   */
  where?: Prisma.EngineWhereInput
  /**
   * Limit how many Engines to update.
   */
  limit?: number
}

/**
 * Engine upsert
 */
export type EngineUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * The filter to search for the Engine to update in case it exists.
   */
  where: Prisma.EngineWhereUniqueInput
  /**
   * In case the Engine found by the `where` argument doesn't exist, create a new Engine with this data.
   */
  create: Prisma.XOR<Prisma.EngineCreateInput, Prisma.EngineUncheckedCreateInput>
  /**
   * In case the Engine was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EngineUpdateInput, Prisma.EngineUncheckedUpdateInput>
}

/**
 * Engine delete
 */
export type EngineDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
  /**
   * Filter which Engine to delete.
   */
  where: Prisma.EngineWhereUniqueInput
}

/**
 * Engine deleteMany
 */
export type EngineDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Engines to delete
   */
  where?: Prisma.EngineWhereInput
  /**
   * Limit how many Engines to delete.
   */
  limit?: number
}

/**
 * Engine without action
 */
export type EngineDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Engine
   */
  select?: Prisma.EngineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Engine
   */
  omit?: Prisma.EngineOmit<ExtArgs> | null
}
